"""Build the final skeleton SK_final.ly from its parts (run after editing any part)."""
import fl
def bars(s):
    return [b.strip() for b in s.replace('\n', ' ').split('|') if b.strip()]

# ---- Part I exposition, bars 1-17 (S-A-B-T permutation exposition) -----------------------------
EXPO = dict(
soprano = bars("""bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. des''8 bes'8 |
c''4. a'8 f'4 c''4 | aes''2. g''4 | f''4 e''4 ees''2 | des''2. c''4 |
e''4. g''8 c''4 r4 | bes'8 a'8 bes'8 c''8 des''8 c''8 ees''8 ges'8 | des''4 c''8 f''8~ f''2 | ees''8 f''8 ees''8 des''8 ces''4 des''4 |
f''2. r4 | r4 c''2 des''4 | c''2 r2 | r4 des''2 f''4 | e''2. d''4"""),
alto = bars("""r1 | r1 | r1 | r1 |
f'2. f'8 e'8 | f'2. f'8 e'8 | f'4. g'8 g'4. bes'8 | bes'2. aes'8 f'8 |
g'4. e'8 c'4 f4 | des'2. c'4 | bes4 a4 aes2 | ges2. f4 |
a4. c'8 a4 r4 | f'8 e'8 f'8 g'8 aes'8 g'8 bes'8 des'8 | aes'4 g'8 c''8~ c''2 | bes'8 c''8 bes'8 aes'8 ges'4 aes'4 | c''1"""),
tenor = bars("""r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 |
f2. f8 e8 | f2. f8 e8 | f4. g8 g4. bes8 | bes2. aes8 f8 | g4. e8 c4 e4"""),
bass = bars("""r1 | r1 | r1 | r1 | r1 | r1 | r1 | r1 |
bes,2. bes,8 a,8 | bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 bes,8 |
c4. a,8 f,4 c,4 | aes,2. g,4 | f,4 e,4 ees,2 | des,2. c,4 | e,4. g,8 c,4 c4"""),
)

# ---- Part V apotheosis, bars 51-60 (= proposal-4 P06) + coda 61-62 --------------------------------
APO = fl.read('../proposal-4/lab/P06_apotheosis_frame.ly')
CODA = dict(
soprano = bars("d''2 c''2 | d''1"),
alto = bars("f'2 ees'2 | d'1"),
tenor = bars("bes2. bes8 a8 | bes1"),
bass = bars("bes,1~ | bes,1"),
)

base = fl.read('../proposal-2/lab/L11_full_skeleton.ly')
sk = fl.splice(base, EXPO, 1)
sk = fl.splice(sk, APO, 51)
sk = fl.splice(sk, CODA, 61)
if __name__ == '__main__':
    fl.write('SK_final.ly', sk, 'FINAL SKELETON (generated by build_sk.py; do not edit by hand)')
    print(fl.nbars(sk), 'bars')
