\version "2.24.0"
% MATERIALS of the final ricercar, one \absolute variable per material at its reference pitch.
% Machine-readable: tools/lyparse.parse_voice(src, NAME) reads any of them. Generated by build_labs.py.
% B-flat minor unless stated; bar lines mark 4/4 bars of the material itself (bar 1 = its first bar).

% themeMinor: reference: the whole theme in B-flat minor (THEME.md), never stated complete in the minor
themeMinor = \absolute {
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. des''8 bes'8 | c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 | c''1 | c''2 r2 |
}

% themeMajor: reference: the theme as the user knows it (THEME.md)
themeMajor = \absolute {
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. d''8 bes'8 | c''4. a'8 f'4 d''8 bes'8 | c''2. f''8 bes'8 | ees''4. d''8 d''4. c''8 | c''1 | c''2 r2 |
}

% subjectOne: S1 = theme bars 1 to 5 beat 3; soprano bar 1
subjectOne = \absolute {
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. des''8 bes'8 | c''4. a'8 f'4 r4 |
}

% answerOne: real answer in F minor; alto bar 5
answerOne = \absolute {
  f'2. f'8 e'8 | f'2. f'8 e'8 | f'4. g'8 g'4. bes'8 | bes'2. aes'8 f'8 | g'4. e'8 c'4 r4 |
}

% csOne: CS1 lament, subject level; alto 9:4 (enters on the subject's beat 4)
csOne = \absolute {
  r2. f4 | des'2. c'4 | bes4 a4 aes2 | ges2. f4 | a4. c'8 f4 r4 |
}

% csOneAnswer: CS1 at the answer level; soprano 5:4
csOneAnswer = \absolute {
  r2. c''4 | aes''2. g''4 | f''4 e''4 ees''2 | des''2. c''4 | e''4. g''8 c''4 r4 |
}

% csTwo: CS2 motor, subject level; soprano bar 10 (landing note free: f'' at bar 13)
csTwo = \absolute {
  r1 | bes'8 a'8 bes'8 c''8 des''8 c''8 ees''8 ges'8 | des''4 c''8 f''8~ f''2 | ees''8 f''8 ees''8 des''8 ces''4 des''4 | f'2. r4 |
}

% csTwoAnswer: CS2 at the answer level; alto bar 14 (landing free: c'' at bar 17)
csTwoAnswer = \absolute {
  r1 | f'8 e'8 f'8 g'8 aes'8 g'8 bes'8 des'8 | aes'4 g'8 c''8~ c''2 | bes'8 c''8 bes'8 aes'8 ges'4 aes'4 | c'2. r4 |
}

% subjectTwo: S2 = theme bars 5-8; soprano bar 30 (arioso), alto bar 42
subjectTwo = \absolute {
  c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 | c''1 |
}

% inversion: INV = tonal mirror of S1 (bes<->f, c<->ees, a<->ges, aes<->g, des fixed); reference pitch
inversion = \absolute {
  f''2. f''8 ges''8 | f''2. f''8 ges''8 | f''4. ees''8 ees''4. c''8 | c''2. des''8 f''8 | ees''4. ges''8 bes''4 r4 |
}

% inversionA: INV in A minor; bass bar 35
inversionA = \absolute {
  e2. e8 f8 | e2. e8 f8 | e4. d8 d4. b,8 | b,2. c8 e8 | d4. f8 a4 r4 |
}

% inversionE: INV in E minor (stretto at the 5th above, 2 bars); tenor bar 37
inversionE = \absolute {
  b2. b8 c'8 | b2. b8 c'8 | b4. a8 a4. fis8 | fis2. g8 b8 | a4. c'8 e'4 r4 |
}

% csOneInv: CS1 inverted (the lament rising), A minor; alto 35:4
csOneInv = \absolute {
  r2. a'4 | c'2. d'4 | e'4 f'4 fis'2 | gis'2. a'4 | f'4. d'8 a'2 |
}

% csTwoInv: CS2 inverted, A minor; soprano bar 36 (three notes altered from the strict mirror)
csTwoInv = \absolute {
  e''8 f''8 e''8 d''8 c''8 d''8 b'8 g''8 | c''4 d''8 a'8~ a'4 b'4 | b'8 a'8 b'8 c''8 d''4 c''4 |
}

% inversionAug: INV in exact 2x augmentation = the dominant pedal; bass bar 42, lands on bes, at 51:1
inversionAug = \absolute {
  f,1 | f,2 f,4 ges,4 | f,1 | f,2 f,4 ges,4 | f,2. ees,4 | ees,2. c,4 | c,1 | c,2 des,4 f,4 | ees,2. ges,4 | bes,2 r2 |
}

% headH: the subject's head, x2. x8 (x-1)8; liquidation on E, G, B-flat, D-flat (26-28)
headH = \absolute {
  e2. e8 ees8 |
}

% episodeCell: cell b = S1 bar 3 rhythm in sequence; soprano bar 18
episodeCell = \absolute {
  c''4. des''8 des''4. f''8 | ges''4. f''8 f''4. ees''8 | des''4 r2. |
}

% descantEntryFour: free soprano over exposition entry 4 (c''-des''-c'' = the INV sigh at the answer level); bar 13
descantEntryFour = \absolute {
  f''2. r4 | r4 c''2 des''4 | c''2 r2 | r4 des''2 f''4 | e''2. d''4 |
}

% lamentLeadIn: tenor lead-in to its S1 entry over the pedal; bar 42
lamentLeadIn = \absolute {
  bes2 a2 | aes2 g4 ges4 |
}

% wedge: soprano 44-50: INV head, inverted pedal, chromatic wedge to the V fermata (a'' at 49:4)
wedge = \absolute {
  f''2. f''8 ges''8 | f''1 | f''1~ | f''2. ges''4~ | ges''2 g''2 | bes''2 bes''4 a''4 | bes''1 |
}

% themeCantusFirmus: the whole theme untouched in B-flat major; its open c'' rises to d''; soprano bar 51
themeCantusFirmus = \absolute {
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. d''8 bes'8 | c''4. a'8 f'4 d''8 bes'8 | c''2. f''8 bes'8 | ees''4. d''8 d''4. c''8 | c''1 | d''1~ | d''1 |
}

% mirrorMajor: melodic mirror of S1 (major) about its first note; bass bar 51 (pickup g,-bes, replaced by d,4)
mirrorMajor = \absolute {
  bes,2. bes,8 c8 | bes,2. bes,8 c8 | bes,4. a,8 a,4. f,8 | f,2. d,4 |
}

% answerMajor: the answer in F major under the tune's second half; bass bar 55
answerMajor = \absolute {
  f,2. f,8 e,8 | f,2. f,8 e,8 | f,4. g,8 g,4. bes,8 | bes,2. a,8 f,8 |
}

% answerMirrorMajor: the answer's mirror = INV in major with e for ees over the F pedal; tenor bar 55
answerMirrorMajor = \absolute {
  f2. f8 g8 | f2. f8 g8 | f4. e8 e4. c8 | c2. d8 f8 |
}

% codaHead: the subject's head as the last word (V7 over the tonic pedal); tenor bar 61
codaHead = \absolute {
  bes2. bes8 a8 | bes1 |
}
