\version "2.24.0"
% FINAL SKELETON (generated by build_sk.py; do not edit by hand)
soprano = \absolute {
  % 1
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. des''8 bes'8 |
  % 5
  c''4. a'8 f'4 c''4 | aes''2. g''4 | f''4 e''4 ees''2 | des''2. c''4 |
  % 9
  e''4. g''8 c''4 r4 | bes'8 a'8 bes'8 c''8 des''8 c''8 ees''8 ges'8 | des''4 c''8 f''8~ f''2 | ees''8 f''8 ees''8 des''8 ces''4 des''4 |
  % 13
  f''2. r4 | r4 c''2 des''4 | c''2 r2 | r4 des''2 f''4 |
  % 17
  e''2. d''4 | c''4. des''8 des''4. f''8 | ges''4. f''8 f''4. ees''8 | des''4 r2. |
  % 21
  r1 | ees''2. ees''8 d''8 | ees''2. ees''8 d''8 | ees''4. f''8 f''4. aes''8 |
  % 25
  aes''2. ges''8 ees''8 | f''4. des''8 bes'4 r4 | r1 | des''2. des''8 c''8 |
  % 29
  c''1 | c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 |
  % 33
  c''1 | c''2 b'2 | r1 | e''8 f''8 e''8 d''8 c''8 d''8 b'8 g''8 |
  % 37
  c''4 d''8 a'8 ~ a'4 b'4 | b'8 a'8 b'8 c''8 d''4 c''4 | f''2 e''4 dis''4 ~ | dis''2. e''4 |
  % 41
  e''2 g''2 | r1 | r1 | r1 |
  % 45
  r1 | r2 f''2 ~ | f''2. ges''4 ~ | ges''2 g''2 |
  % 49
  bes''2 bes''4 a''4 | bes''1 | bes'2. bes'8 a'8 | bes'2. bes'8 a'8 |
  % 53
  bes'4. c''8 c''4. ees''8 | ees''2. d''8 bes'8 | c''4. a'8 f'4 d''8 bes'8 | c''2. f''8 bes'8 |
  % 57
  ees''4. d''8 d''4. c''8 | c''1 | d''1~ | d''1 |
  % 61
  d''2 c''2 | d''1 |
}
alto = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  f'2. f'8 e'8 | f'2. f'8 e'8 | f'4. g'8 g'4. bes'8 | bes'2. aes'8 f'8 |
  % 9
  g'4. e'8 c'4 f4 | des'2. c'4 | bes4 a4 aes2 | ges2. f4 |
  % 13
  a4. c'8 a4 r4 | f'8 e'8 f'8 g'8 aes'8 g'8 bes'8 des'8 | aes'4 g'8 c''8~ c''2 | bes'8 c''8 bes'8 aes'8 ges'4 aes'4 |
  % 17
  c''1 | aes'2 bes'2 | bes'2 a'2 | f'1 |
  % 21
  des''2. c''4 | bes'4 a'4 aes'2 | ges'2. f'4 | aes'4. c''8 f'4 f'4 |
  % 25
  f'2 bes'2 | bes'2 g'2 ~ | g'2 bes'2 ~ | bes'4 bes'8 a'8 ~ a'2 ~ |
  % 29
  a'1 | c'8 c'8 c'8 c'8 c'8 c'8 des'8 des'8 | ees'8 ees'8 ees'8 ees'8 ees'8 ees'8 f'8 f'8 | ges'8 ges'8 ges'8 ges'8 ees'8 ees'8 ees'8 ees'8 |
  % 33
  ees'8 ees'8 ees'8 ees'8 ees'8 ees'8 ees'8 ees'8 | e'8 e'8 e'8 e'8 e'8 e'8 e'8 e'8 | r2. a'4 | c'2. d'4 |
  % 37
  e'4 f'4 fis'2 | gis'2. a'4 | f'4. d'8 a'2 | a'2. g'4 |
  % 41
  g'2 c''4 e''4 | c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 |
  % 45
  c''1 | des''2 c''2 | a'2 c''4 ees''4 | ees''2 e''2 |
  % 49
  e''2. c''4 | ees'2. ees'4 | d'4. ees'8 f'4 ees'4 | d'4 f'4 ees'4 f'8 ees'8 |
  % 53
  f'4. ees'8 ees'4. f'8 | a'2 g'4 f'4~ | f'4 e'4 d'4 e'4~ | e'4 ees'4 f'2 |
  % 57
  c''2. bes'4~ | bes'4 a'4 g'2 | f'1 | ges'2 f'2 |
  % 61
  f'2 ees'2 | d'1 |
}
tenor = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 | r1 |
  % 9
  r1 | r1 | r1 | r1 |
  % 13
  f2. f8 e8 | f2. f8 e8 | f4. g8 g4. bes8 | bes2. aes8 f8 |
  % 17
  g4. e8 c4 e4 | f2 des'2 | ees'2 c'2 | bes4 r2. |
  % 21
  bes8 a8 bes8 c'8 des'8 c'8 ees'8 ges8 | des'4 c'8 f'8 ~ f'2 | ees'8 f'8 ees'8 des'8 ces'4 aes4 | ees'2 aes2 |
  % 25
  aes2 bes2 | bes1 | g2. g8 ges8 | ges1 ~ |
  % 29
  ges1 | f8 f8 f8 f8 a8 a8 bes8 bes8 | ges8 ges8 ges8 ges8 ges8 ges8 f8 f8 | bes8 bes8 bes8 bes8 a8 a8 a8 a8 |
  % 33
  a8 a8 a8 a8 a8 a8 a8 a8 | gis8 gis8 gis8 gis8 gis8 gis8 gis8 gis8 | r1 | r1 |
  % 37
  b2. b8 c'8 | b2. b8 c'8 | b4. a8 a4. fis8 | fis2. g8 b8 |
  % 41
  a4. c'8 e'4 c'4 | r1 | r1 | bes2. bes8 a8 |
  % 45
  bes2. bes8 a8 | bes4. c'8 c'4. ees'8 | ees'2. des'8 bes8 | c'4. a8 bes2 ~ |
  % 49
  bes2. c'4 | g2. ges4 | f2 g4 f4 | bes4 aes4 g4 f4 |
  % 53
  f4 d'4 c'4. c'8 | c'2. f4 | f2. f8 g8 | f2. f8 g8 |
  % 57
  f4. e8 e4. c8 | c2. d8 f8 | d'1 | ees'2 d'2 |
  % 61
  bes2. bes8 a8 | bes1 |
}
bass = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 | r1 |
  % 9
  bes,2. bes,8 a,8 | bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 bes,8 |
  % 13
  c4. a,8 f,4 c,4 | aes,2. g,4 | f,4 e,4 ees,2 | des,2. c,4 |
  % 17
  e,4. g,8 c,4 c4 | f,2 bes,2 | ees,2 f,2 | bes,2. bes,8 a,8 |
  % 21
  bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 bes,8 | c4. aes,8 f,4 ees,4 |
  % 25
  des,2. c,4 | f,2 e,2 ~ | e,4 e,8 ees,8 ~ ees,2 ~ | ees,1 ~ |
  % 29
  ees,1 | f,1 | ees,2. d,4 | ges,2 f,2 |
  % 33
  f,1 | e,1 | e2. e8 f8 | e2. e8 f8 |
  % 37
  e4. d8 d4. b,8 | b,2. c8 e8 | d4. f8 a4 fis4 | b,2. e4 |
  % 41
  c2. c4 | f,1 | f,2 f,4 ges,4 | f,1 |
  % 45
  f,2 f,4 ges,4 | f,2. ees,4 | ees,2. c,4 | c,1 |
  % 49
  c,2 des,4 f,4 | ees,2. ges,4 | bes,2. bes,8 c8 | bes,2. bes,8 c8 |
  % 53
  bes,4. a,8 a,4. f,8 | f,2. d,4 | f,2. f,8 e,8 | f,2. f,8 e,8 |
  % 57
  f,4. g,8 g,4. bes,8 | bes,2. a,8 f,8 | bes,1~ | bes,1 |
  % 61
  bes,1~ | bes,1 |
}
