\version "2.24.0"
% X2_stretto_S1_4th: S1 stretto: bass b-flat (20) and soprano e-flat a 4th + 2 octaves above, 2 bars later (20-26)
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  des''4 r2. | r1 | ees''2. ees''8 d''8 | ees''2. ees''8 d''8 |
  % 5
  ees''4. f''8 f''4. aes''8 | aes''2. ges''8 ees''8 | f''4. des''8 bes'4 r4 |
}
alto = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 |
}
tenor = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 |
}
bass = \absolute {
  % 1
  bes,2. bes,8 a,8 | bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 bes,8 |
  % 5
  c4. aes,8 f,4 ees,4 | des,2. c,4 | f,2 e,2 ~ |
}
