\version "2.24.0"
% X3_liquidation: head H on E, G, B-flat, D-flat at half-bar distances: E dim7 slides to A dim7 (26-29)
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  f''4. des''8 bes'4 r4 | r1 | des''2. des''8 c''8 | c''1 |
}
alto = \absolute {
  % 1
  bes'2 g'2 ~ | g'2 bes'2 ~ | bes'4 bes'8 a'8 ~ a'2 ~ | a'1 |
}
tenor = \absolute {
  % 1
  bes1 | g2. g8 ges8 | ges1 ~ | ges1 |
}
bass = \absolute {
  % 1
  f,2 e,2 ~ | e,4 e,8 ees,8 ~ ees,2 ~ | ees,1 ~ | ees,1 |
}
