\version "2.24.0"
% X6_S2_then_S1: S2 (alto 42) with S1 two bars later (tenor 44), the pair alone (42-48)
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 |
}
alto = \absolute {
  % 1
  c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 | c''1 |
  % 5
  des''2 c''2 | a'2 c''4 ees''4 | ees''2 e''2 |
}
tenor = \absolute {
  % 1
  bes2 a2 | aes2 g4 ges4 | bes2. bes8 a8 | bes2. bes8 a8 |
  % 5
  bes4. c'8 c'4. ees'8 | ees'2. des'8 bes8 | c'4. a8 bes2 ~ |
}
bass = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 |
}
