\version "2.24.0"
% X7_combination_pedal: S2 + S1 + INV head + INV in augmentation (the pedal), with the wedge (42-50)
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  r1 | r1 | f''2. f''8 ges''8 | f''1 |
  % 5
  f''1~ | f''2. ges''4 ~ | ges''2 g''2 | bes''2 bes''4 a''4 |
  % 9
  bes''1 |
}
alto = \absolute {
  % 1
  c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 | ees''4. des''8 des''4. c''8 | c''1 |
  % 5
  des''2 c''2 | a'2 c''4 ees''4 | ees''2 e''2 | e''2. c''4 |
  % 9
  ees'2. ees'4 |
}
tenor = \absolute {
  % 1
  bes2 a2 | aes2 g4 ges4 | bes2. bes8 a8 | bes2. bes8 a8 |
  % 5
  bes4. c'8 c'4. ees'8 | ees'2. des'8 bes8 | c'4. a8 bes2 ~ | bes2. c'4 |
  % 9
  g2. ges4 |
}
bass = \absolute {
  % 1
  f,1 | f,2 f,4 ges,4 | f,1 | f,2 f,4 ges,4 |
  % 5
  f,2. ees,4 | ees,2. c,4 | c,1 | c,2 des,4 f,4 |
  % 9
  ees,2. ges,4 |
}
