\version "2.24.0"
% X8_tune_over_mirror: apotheosis: the whole tune (major) over its mirror, then over the answer (51-59)
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. d''8 bes'8 |
  % 5
  c''4. a'8 f'4 d''8 bes'8 | c''2. f''8 bes'8 | ees''4. d''8 d''4. c''8 | c''1 |
  % 9
  d''1~ |
}
alto = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 | r1 |
  % 9
  r1 |
}
tenor = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
  % 5
  r1 | r1 | r1 | r1 |
  % 9
  r1 |
}
bass = \absolute {
  % 1
  bes,2. bes,8 c8 | bes,2. bes,8 c8 | bes,4. a,8 a,4. f,8 | f,2. d,4 |
  % 5
  f,2. f,8 e,8 | f,2. f,8 e,8 | f,4. g,8 g,4. bes,8 | bes,2. a,8 f,8 |
  % 9
  bes,1~ |
}
