\version "2.24.0"
% X9_answer_vs_mirror: apotheosis: the answer (bass) against its own mirror (tenor), bars 55-58
% Generated by build_labs.py from materials/SK_final.ly; do not edit by hand.
soprano = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
}
alto = \absolute {
  % 1
  r1 | r1 | r1 | r1 |
}
tenor = \absolute {
  % 1
  f2. f8 g8 | f2. f8 g8 | f4. e8 e4. c8 | c2. d8 f8 |
}
bass = \absolute {
  % 1
  f,2. f,8 e,8 | f,2. f,8 e,8 | f,4. g,8 g,4. bes,8 | bes,2. a,8 f,8 |
}
