% Proposal 3, lab 99: all section labs spliced by time into one 62-bar file (integrity check).
% GENERATED by assemble_check.py from labs 01, 14, 13, 12, 10, 08, 09.
soprano = \absolute {
  R1 | R1 | R1 | R1 |
  R1 | R1 | R1 | R1 |
  R1 | R1 | R1 | R1 |
  R1 | f''2. f''8 e''8 | f''2. f''8 e''8 | f''4. g''8 g''4. bes''8 |
  bes''2. aes''8 g''8 | f''8 ees''8 des''8 c''8 ees''8 des''8 c''8 bes'8 | des''8 c''8 bes'8 a'8 c''4 r4 | R1 |
  R1 | R1 | R1 | r2 f''4. d''8 |
  bes'4 ges''8 ees''8 f''2~ | f''4 bes''8 ees''8 aes''4. ges''8 | ges''4. f''8 f''2 | f''2 r2 |
  r2 g''4. e''8 | c''4 aes''8 f''8 g''2~ | g''4 c'''8 f''8 bes''4. aes''8 | aes''4. g''8 g''2~ |
  g''2 aes''2 | a''2 ces'''2 | R1 | R1 |
  R1 | R1 | f''2. f''8 ges''8 | f''2. f''8 ges''8 |
  f''4. ees''8 ees''4. c''8 | c''2. des''8 ees''8 | bes''2. bes''8 ces'''8 | bes''2. bes''8 ces'''8 |
  bes''4. aes''8 aes''4. f''8 | f''2. ges''8 aes''8 | a''2. bes''4~ | bes''2. aes''4 |
  ges''2 f''2 | g''2 aes''4 c'''4 | c'''2 a''4 c''4 | bes'2. bes'8 a'8 |
  bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 | ees''2. d''8 bes'8 | c''4. a'8 f'4 d''8 bes'8 |
  c''2. f''8 bes'8 | ees''4. d''8 d''4. c''8 | c''1 | c''2 d''2 |
  bes'2. bes'8 a'8 | bes'1 |
}
alto = \absolute {
  R1 | R1 | R1 | R1 |
  R1 | R1 | R1 | R1 |
  R1 | bes'2. bes'8 a'8 | bes'2. bes'8 a'8 | bes'4. c''8 c''4. ees''8 |
  ees''2. des''8 c''8 | bes'2 d''2 | des''2 c''2 | b'2 c''2 |
  des''2 c''2 | c''4 aes'4 bes'2 | bes'4 ges'8 f'8 ees'4 r4 | r2 c''4. a'8 |
  f'4 des''8 bes'8 c''2~ | c''4 f''8 bes'8 ees''4. des''8 | des''4. c''8 c''2~ | c''4 bes'4 r2 |
  R1 | f'4 g'4 ees'2 | ees'4 c''2 c''4 | des''2 c''4. a'8 |
  f'4 des''8 bes'8 c''2~ | c''4 f''8 bes'8 ees''4. des''8 | des''4. c''8 c''2~ | c''2 ees''2~ |
  ees''4 des''4 d''2 | ees''2 ees''2 | r4 des'2 ees'4~ | ees'4 f'2 ges'4~ |
  ges'4 aes'2 bes'4~ | bes'4 ces''2 aes'4~ | aes'1 | a'2 bes'2 |
  ces''2 bes'2 | a'2 bes'2 | bes'2. bes'8 a'8 | bes'2. bes'8 a'8 |
  bes'4. c''8 c''4. ees''8 | ees''2. des''8 bes'8 | c''4. a'8 f'4 des''8 bes'8 | c''2. f''8 bes'8 |
  ees''4. des''8 des''4. c''8 | c''1 | c''2 f'2 | d'4 g'2 f'4~ |
  f'4 ees'2 d'4~ | d'4 c'2 bes4~ | bes4 a4 f'2~ | f'4 f'8 e'8 f'2~ |
  f'4 f'8 e'8 f'4. g'8 | g'4. bes'8 bes'2~ | bes'4 a'8 g'8 f'2 | ees'2 d'2 |
  d'2 ees'2 | d'1 |
}
tenor = \absolute {
  R1 | R1 | R1 | R1 |
  f'2. f'8 e'8 | f'2. f'8 e'8 | f'4. g'8 g'4. bes'8 | bes'2. aes'8 g'8 |
  f'4 ees'4 des'4 c'4 | f'2 g'2 | ges'2 f'2 | e'2 f'2 |
  ges'2 f'2 | f'4 d'2 c'4~ | c'4 bes2 aes4~ | aes4 g2 f4~ |
  f4 e2 g4 | aes2 g2 | f2 a4 r4 | f'2. f'8 e'8 |
  f'2. f'8 e'8 | f'4. g'8 g'4. bes'8 | bes'2. aes'8 g'8 | f'4 g'2 f'4~ |
  f'4 ees'2 des'4~ | des'4 c'2 bes4~ | bes4 a2 c'4 | f2. f8 e8 |
  f2. f8 e8 | f4. g8 g4. bes8 | bes2. aes8 g8 | f2 bes4 c'4 |
  c'4 des'4 f'2 | ges'2 ges'2 | bes2. bes8 ces'8 | bes2. bes8 ces'8 |
  bes4. aes8 aes4. f8 | f2. ges8 aes8 | bes4 aes2 bes4~ | bes4 c'2 des'4~ |
  des'4 ees'2 f'4~ | f'4 ges'2 ees'4 | f'4 g'2 f'4~ | f'4 ees'2 des'4~ |
  des'4 c'2 bes4~ | bes4 a2 c'4 | c'2. e'4~ | e'2. f'4 |
  ges'2 aes'2 | g'2 f'4 e'4 | f'1 | f1 |
  g2. f4 | f1 | g4 f4 a4 bes4 | a2. bes4 |
  f2. g4 | bes2 d'4 c'4~ | c'1 | a2 bes2 |
  f2 ges2 | f1 |
}
bass = \absolute {
  bes,2. bes,8 a,8 | bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 c8 |
  bes,2 d2 | des2 c2 | b,2 c2 | des2 c2 |
  f4 c4 bes,4 a,4 | bes,4 g2 f4~ | f4 ees2 des4~ | des4 c2 bes,4~ |
  bes,4 a,2 f,4 | bes,1 | des2 f2 | d2 c2 |
  bes,2 c2 | f,1~ | f,1 | f4 d2 c4~ |
  c4 bes,2 aes,4~ | aes,4 g,2 f,4~ | f,4 e,2 f,4 | bes,2. bes,8 a,8 |
  bes,2. bes,8 a,8 | bes,4. c8 c4. ees8 | ees2. des8 c8 | bes,2 r2 |
  R1 | R1 | R1 | f,2 g,4 aes,4 |
  a,4 bes,4 b,2 | c2 ces2 | r2 des,2 | d,2 ees,2 |
  fes,2 ees,2 | d,2 ees,2 | bes,1~ | bes,1 |
  des,2 ees,2 | f,2 ges,2 | f,1~ | f,2 f,4 e,4 |
  f,1~ | f,2 f,4 e,4 | f,2. g,4 | g,2. bes,4 |
  bes,1~ | bes,2 aes,4 ges,4 | f,1 | bes,1 |
  bes,1 | bes,2 f2 | ees2 f4 d4~ | d4 c2 bes,4~ |
  bes,4 a,2 g,4~ | g,4 f,2 e,4~ | e,4 g,4 a,2 | f,2 bes,2 |
  bes,1 | bes,1 |
}
