% GENERATED by tools/make_global.py from design/final-lab/plan.json and score/sections/ -- do not edit by hand.
% \global: key, time, tempo marks and ramps, fermatas, breaths; \marks: rehearsal numbers = blueprint
% section numbers; \dynamicsLine: the plan's dynamics and hairpins as spacer rests (66 bars).

subPP = #(make-dynamic-script #{ \markup { \normal-text \italic "subito" \dynamic pp } #})
subPMist = #(make-dynamic-script #{ \markup { \normal-text \italic "subito" \dynamic p \normal-text \italic "misterioso" } #})
pDolce = #(make-dynamic-script #{ \markup { \dynamic p \normal-text \italic "dolce" } #})
crescPoco = #(make-music 'CrescendoEvent 'span-direction START 'span-type 'text 'span-text "cresc. poco a poco")
dimPoco = #(make-music 'DecrescendoEvent 'span-direction START 'span-type 'text 'span-text "dim. poco a poco")

global = {
  %1
  \time 4/4 \key bes \minor \tempo \markup { "Grave e sostenuto" } 4 = 78 s1 |
  s1 |
  s1 |
  s1 |
  %5
  s1 |
  s1 |
  s1 |
  s1 |
  %9
  s1 |
  s1 |
  s1 |
  s1 |
  %13
  s1 |
  s1 |
  s1 |
  s1 |
  %17
  s1 |
  s1 |
  s1 |
  s1 |
  %21
  s1 |
  s1 |
  s1 |
  s1 |
  %25
  s1 |
  s1 |
  s1 |
  %28
  \tempo \markup { \normal-text \italic "rit." } s1 |
  %29
  s1^\markup { \musicglyph "scripts.ufermata" } \bar "||" \once \override BreathingSign.text = \markup { \musicglyph "scripts.caesura.straight" } \breathe |
  %30
  \tempo \markup { "Arioso dolente" } 4 = 52 s1 |
  s1 |
  s1 |
  %33
  s1 |
  s1 \bar "||" \breathe |
  %35
  \tempo \markup { "Fuga inversa" \normal-text \italic "poi a poi di nuovo vivente" } 4 = 64 s1 |
  s1 |
  %37
  s1 |
  s1 |
  s1 |
  s1 |
  %41
  s1 |
  s1 |
  s1 |
  s1 |
  %45
  s1 \bar "||" \breathe |
  %46
  \tempo 4 = 76 s1 |
  s1 |
  s1 |
  %49
  s1 |
  s1 |
  s1 |
  s1 |
  %53
  \tempo \markup { \normal-text \italic "rit." } s2. s4^\markup { \musicglyph "scripts.ufermata" } |
  %54
  \tempo \markup { "Meno mosso" \normal-text \italic "rit." } 4 = 62 s1 \bar "||" |
  %55
  \key bes \major \tempo \markup { "Largamente" } 4 = 72 s1 |
  s1 |
  %57
  s1 |
  s1 |
  s1 |
  s1 |
  %61
  s1 |
  s1 |
  %63
  \tempo \markup { \normal-text \italic "rit." } s1 |
  s1 |
  %65
  s1 |
  s2 s2^\markup { \musicglyph "scripts.ufermata" } \bar "|."
}

marks = {
  %1
  \set Score.rehearsalMarkFormatter = #format-mark-box-numbers \mark \default s1 |
  s1 |
  s1 |
  s1 |
  %5
  s1 |
  s1 |
  s1 |
  s1 |
  %9
  s1 |
  s1 |
  s1 |
  s1 |
  %13
  \mark \default s1 |
  s1 |
  s1 |
  s1 |
  %17
  s1 |
  s1 |
  s1 |
  %20
  \mark \default s1 |
  %21
  s1 |
  s1 |
  s1 |
  s1 |
  %25
  s1 |
  s1 |
  s1 |
  s1 |
  %29
  s1 |
  %30
  \mark \default s1 |
  s1 |
  s1 |
  %33
  s1 |
  s1 |
  %35
  \mark \default s1 |
  s1 |
  %37
  s1 |
  s1 |
  s1 |
  s1 |
  %41
  s1 |
  s1 |
  s1 |
  s1 |
  %45
  s1 |
  %46
  \mark \default s1 |
  s1 |
  s1 |
  %49
  s1 |
  s1 |
  s1 |
  s1 |
  %53
  s1 |
  s1 |
  %55
  \mark \default s1 |
  s1 |
  %57
  s1 |
  s1 |
  s1 |
  s1 |
  %61
  s1 |
  s1 |
  s1 |
  s1 |
  %65
  s1 |
  s1
}

dynamicsLine = {
  %1
  s1\p |
  s1 |
  s1 |
  s1 |
  %5
  s1\crescPoco |
  s1 |
  s1 |
  s1 |
  %9
  s1 |
  s1 |
  s1 |
  s1 |
  %13
  s1\mp\< |
  s1 |
  s1 |
  s1 |
  %17
  s2 s2\mf |
  %18
  s1\mp |
  s1 |
  %20
  s1\crescPoco |
  %21
  s1 |
  s1 |
  s1 |
  s1 |
  %25
  s1 |
  %26
  s2\f s2\< |
  s1 |
  %28
  s1\ff |
  %29
  s1 |
  %30
  s1\subPP\< |
  s1 |
  %32
  s1\mp\> |
  %33
  s1 |
  %34
  s1\pp |
  %35
  s1\crescPoco |
  s1 |
  %37
  s1 |
  s1 |
  s1 |
  s1 |
  %41
  s1 |
  s1 |
  s1 |
  s1 |
  %45
  s2 s2\mf |
  %46
  s1\subPMist |
  s1 |
  %48
  s1\< |
  %49
  s1 |
  %50
  s1\mp\< |
  s1 |
  %52
  s1\f\< |
  %53
  s2. s4\fff |
  %54
  s1\f\> |
  %55
  s1\pDolce\< |
  s1 |
  %57
  s1 |
  s1 |
  %59
  s1\mf\< |
  s2. s4\f |
  %61
  s2 s2\> |
  s1 |
  %63
  s1\mp\> |
  s1 |
  %65
  s1 |
  s2 s2\pp
}
